import json
import os

from web3 import Web3

CONTRACT_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "contracts",
    "Voting.json",
)

_contract = None


def load_contract():
    """Returns (abi, bytecode) of the pre-compiled Voting contract.

    The artifact is generated by compile_contract.py and committed to the
    repository, so no Solidity compiler is needed at runtime.
    """
    global _contract
    if _contract is None:
        with open(CONTRACT_PATH) as artifact_file:
            artifact = json.load(artifact_file)
        _contract = (artifact["abi"], artifact["bytecode"])
    return _contract


def is_valid_address(value):
    return isinstance(value, str) and Web3.is_address(value)


def deploy_voting_contract(web3, voters):
    """Deploys a Voting contract for the given voters and returns its address."""
    abi, bytecode = load_contract()
    contract = web3.eth.contract(abi=abi, bytecode=bytecode)
    addresses = [Web3.to_checksum_address(voter) for voter in voters]

    tx_hash = contract.constructor(addresses).transact({"from": web3.eth.accounts[0]})
    receipt = web3.eth.wait_for_transaction_receipt(tx_hash)
    return receipt.contractAddress


def build_vote_transactions(web3, address):
    """Returns the unsigned (approve, reject) transactions for a deployed contract."""
    abi, _ = load_contract()
    contract = web3.eth.contract(address=address, abi=abi)
    return (
        {"to": address, "data": contract.encode_abi("vote", args=[True])},
        {"to": address, "data": contract.encode_abi("vote", args=[False])},
    )


def read_voting_result(web3, address):
    """Returns (finished, approved) for a deployed contract."""
    abi, _ = load_contract()
    contract = web3.eth.contract(address=address, abi=abi)
    return contract.functions.finished().call(), contract.functions.approved().call()
